version: '3'
name: laravel-project
services:
    php:
        build: .docker/php
        ports:
            - '5173:5173'
        volumes:
            - '.:/var/www:cached'
    nginx:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - '.:/var/www'
            - '.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - '.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        depends_on:
            - php
    db:
        image: 'mysql:8.1'
        ports:
            - '3307:3306'
        volumes:
            - '.docker/db/data:/var/lib/mysql'
            - '.docker/logs:/var/log/mysql'
            - '.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
            - '.docker/db/sql:/docker-entrypoint-initdb.d'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: refactorian
            MYSQL_USER: refactorian
            MYSQL_PASSWORD: refactorian
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - '.docker/phpmyadmin/sessions:/sessions'
    adminer:
        image: adminer
        ports:
            - '9090:8080'
        depends_on:
            - db
    mail:
        image: 'axllent/mailpit:latest'
        ports:
            - '8025:8025'
            - '1025:1025'
    redis:
        image: 'redis:latest'
        command: 'redis-server --appendonly yes'
        volumes:
            - '.docker/redis/data:/data'
        ports:
            - '6379:6379'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3308}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
volumes:
    sail-mysql:
        driver: local
networks:
    sail: